# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/johnson/Programming/simple-unix-chat

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/johnson/Programming/simple-unix-chat

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/johnson/Programming/simple-unix-chat/CMakeFiles /home/johnson/Programming/simple-unix-chat/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/johnson/Programming/simple-unix-chat/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named succlient

# Build rule for target.
succlient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 succlient
.PHONY : succlient

# fast build rule for target.
succlient/fast:
	$(MAKE) -f CMakeFiles/succlient.dir/build.make CMakeFiles/succlient.dir/build
.PHONY : succlient/fast

#=============================================================================
# Target rules for targets named sucserver

# Build rule for target.
sucserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sucserver
.PHONY : sucserver

# fast build rule for target.
sucserver/fast:
	$(MAKE) -f CMakeFiles/sucserver.dir/build.make CMakeFiles/sucserver.dir/build
.PHONY : sucserver/fast

client/ChatRoom.o: client/ChatRoom.cpp.o

.PHONY : client/ChatRoom.o

# target to build an object file
client/ChatRoom.cpp.o:
	$(MAKE) -f CMakeFiles/succlient.dir/build.make CMakeFiles/succlient.dir/client/ChatRoom.cpp.o
.PHONY : client/ChatRoom.cpp.o

client/ChatRoom.i: client/ChatRoom.cpp.i

.PHONY : client/ChatRoom.i

# target to preprocess a source file
client/ChatRoom.cpp.i:
	$(MAKE) -f CMakeFiles/succlient.dir/build.make CMakeFiles/succlient.dir/client/ChatRoom.cpp.i
.PHONY : client/ChatRoom.cpp.i

client/ChatRoom.s: client/ChatRoom.cpp.s

.PHONY : client/ChatRoom.s

# target to generate assembly for a file
client/ChatRoom.cpp.s:
	$(MAKE) -f CMakeFiles/succlient.dir/build.make CMakeFiles/succlient.dir/client/ChatRoom.cpp.s
.PHONY : client/ChatRoom.cpp.s

client/UserInterface.o: client/UserInterface.cpp.o

.PHONY : client/UserInterface.o

# target to build an object file
client/UserInterface.cpp.o:
	$(MAKE) -f CMakeFiles/succlient.dir/build.make CMakeFiles/succlient.dir/client/UserInterface.cpp.o
.PHONY : client/UserInterface.cpp.o

client/UserInterface.i: client/UserInterface.cpp.i

.PHONY : client/UserInterface.i

# target to preprocess a source file
client/UserInterface.cpp.i:
	$(MAKE) -f CMakeFiles/succlient.dir/build.make CMakeFiles/succlient.dir/client/UserInterface.cpp.i
.PHONY : client/UserInterface.cpp.i

client/UserInterface.s: client/UserInterface.cpp.s

.PHONY : client/UserInterface.s

# target to generate assembly for a file
client/UserInterface.cpp.s:
	$(MAKE) -f CMakeFiles/succlient.dir/build.make CMakeFiles/succlient.dir/client/UserInterface.cpp.s
.PHONY : client/UserInterface.cpp.s

client/main.o: client/main.cpp.o

.PHONY : client/main.o

# target to build an object file
client/main.cpp.o:
	$(MAKE) -f CMakeFiles/succlient.dir/build.make CMakeFiles/succlient.dir/client/main.cpp.o
.PHONY : client/main.cpp.o

client/main.i: client/main.cpp.i

.PHONY : client/main.i

# target to preprocess a source file
client/main.cpp.i:
	$(MAKE) -f CMakeFiles/succlient.dir/build.make CMakeFiles/succlient.dir/client/main.cpp.i
.PHONY : client/main.cpp.i

client/main.s: client/main.cpp.s

.PHONY : client/main.s

# target to generate assembly for a file
client/main.cpp.s:
	$(MAKE) -f CMakeFiles/succlient.dir/build.make CMakeFiles/succlient.dir/client/main.cpp.s
.PHONY : client/main.cpp.s

common/Connection.o: common/Connection.cpp.o

.PHONY : common/Connection.o

# target to build an object file
common/Connection.cpp.o:
	$(MAKE) -f CMakeFiles/succlient.dir/build.make CMakeFiles/succlient.dir/common/Connection.cpp.o
	$(MAKE) -f CMakeFiles/sucserver.dir/build.make CMakeFiles/sucserver.dir/common/Connection.cpp.o
.PHONY : common/Connection.cpp.o

common/Connection.i: common/Connection.cpp.i

.PHONY : common/Connection.i

# target to preprocess a source file
common/Connection.cpp.i:
	$(MAKE) -f CMakeFiles/succlient.dir/build.make CMakeFiles/succlient.dir/common/Connection.cpp.i
	$(MAKE) -f CMakeFiles/sucserver.dir/build.make CMakeFiles/sucserver.dir/common/Connection.cpp.i
.PHONY : common/Connection.cpp.i

common/Connection.s: common/Connection.cpp.s

.PHONY : common/Connection.s

# target to generate assembly for a file
common/Connection.cpp.s:
	$(MAKE) -f CMakeFiles/succlient.dir/build.make CMakeFiles/succlient.dir/common/Connection.cpp.s
	$(MAKE) -f CMakeFiles/sucserver.dir/build.make CMakeFiles/sucserver.dir/common/Connection.cpp.s
.PHONY : common/Connection.cpp.s

server/ClientConnection.o: server/ClientConnection.cpp.o

.PHONY : server/ClientConnection.o

# target to build an object file
server/ClientConnection.cpp.o:
	$(MAKE) -f CMakeFiles/sucserver.dir/build.make CMakeFiles/sucserver.dir/server/ClientConnection.cpp.o
.PHONY : server/ClientConnection.cpp.o

server/ClientConnection.i: server/ClientConnection.cpp.i

.PHONY : server/ClientConnection.i

# target to preprocess a source file
server/ClientConnection.cpp.i:
	$(MAKE) -f CMakeFiles/sucserver.dir/build.make CMakeFiles/sucserver.dir/server/ClientConnection.cpp.i
.PHONY : server/ClientConnection.cpp.i

server/ClientConnection.s: server/ClientConnection.cpp.s

.PHONY : server/ClientConnection.s

# target to generate assembly for a file
server/ClientConnection.cpp.s:
	$(MAKE) -f CMakeFiles/sucserver.dir/build.make CMakeFiles/sucserver.dir/server/ClientConnection.cpp.s
.PHONY : server/ClientConnection.cpp.s

server/Server.o: server/Server.cpp.o

.PHONY : server/Server.o

# target to build an object file
server/Server.cpp.o:
	$(MAKE) -f CMakeFiles/sucserver.dir/build.make CMakeFiles/sucserver.dir/server/Server.cpp.o
.PHONY : server/Server.cpp.o

server/Server.i: server/Server.cpp.i

.PHONY : server/Server.i

# target to preprocess a source file
server/Server.cpp.i:
	$(MAKE) -f CMakeFiles/sucserver.dir/build.make CMakeFiles/sucserver.dir/server/Server.cpp.i
.PHONY : server/Server.cpp.i

server/Server.s: server/Server.cpp.s

.PHONY : server/Server.s

# target to generate assembly for a file
server/Server.cpp.s:
	$(MAKE) -f CMakeFiles/sucserver.dir/build.make CMakeFiles/sucserver.dir/server/Server.cpp.s
.PHONY : server/Server.cpp.s

server/main.o: server/main.cpp.o

.PHONY : server/main.o

# target to build an object file
server/main.cpp.o:
	$(MAKE) -f CMakeFiles/sucserver.dir/build.make CMakeFiles/sucserver.dir/server/main.cpp.o
.PHONY : server/main.cpp.o

server/main.i: server/main.cpp.i

.PHONY : server/main.i

# target to preprocess a source file
server/main.cpp.i:
	$(MAKE) -f CMakeFiles/sucserver.dir/build.make CMakeFiles/sucserver.dir/server/main.cpp.i
.PHONY : server/main.cpp.i

server/main.s: server/main.cpp.s

.PHONY : server/main.s

# target to generate assembly for a file
server/main.cpp.s:
	$(MAKE) -f CMakeFiles/sucserver.dir/build.make CMakeFiles/sucserver.dir/server/main.cpp.s
.PHONY : server/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... sucserver"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... succlient"
	@echo "... client/ChatRoom.o"
	@echo "... client/ChatRoom.i"
	@echo "... client/ChatRoom.s"
	@echo "... client/UserInterface.o"
	@echo "... client/UserInterface.i"
	@echo "... client/UserInterface.s"
	@echo "... client/main.o"
	@echo "... client/main.i"
	@echo "... client/main.s"
	@echo "... common/Connection.o"
	@echo "... common/Connection.i"
	@echo "... common/Connection.s"
	@echo "... server/ClientConnection.o"
	@echo "... server/ClientConnection.i"
	@echo "... server/ClientConnection.s"
	@echo "... server/Server.o"
	@echo "... server/Server.i"
	@echo "... server/Server.s"
	@echo "... server/main.o"
	@echo "... server/main.i"
	@echo "... server/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

